services:
  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    repo: https://github.com/sumanbisunkhe/ecommerce-system-backend
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xms256m -Xmx512m"
